In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("Train.csv")
test = pd.read_csv('Test.csv')
ss = pd.read_csv("SampleSubmission.csv")
train.head()

ID                                               text  target
0  train_0            The bitcoin halving is cancelled due to       1
1  train_1  MercyOfAllah In good times wrapped in its gran...       0
2  train_2  266 Days No Digital India No Murder of e learn...       1
3  train_3  India is likely to run out of the remaining RN...       1
4  train_4  In these tough times the best way to grow is t...       0

In [3]:
X = train['text']
y = train['target']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
vectorizer = CountVectorizer()

In [6]:
X.head()

0              The bitcoin halving is cancelled due to
1    MercyOfAllah In good times wrapped in its gran...
2    266 Days No Digital India No Murder of e learn...
3    India is likely to run out of the remaining RN...
4    In these tough times the best way to grow is t...
Name: text, dtype: object

In [7]:
X = vectorizer.fit_transform(X)

In [8]:
X

<5287x14292 sparse matrix of type '<class 'numpy.int64'>'
	with 92753 stored elements in Compressed Sparse Row format>

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)

In [12]:
from sklearn.svm import SVC

In [13]:
svm = SVC(probability=True)

In [14]:
svm.fit(X_train, y_train)

SVC(probability=True)

In [15]:
pred = svm.predict(X_test)

In [16]:
pred

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,

In [17]:
accuracy_score(y_test, pred)

0.8752362948960303

# Les donnees test pour creer le fichier soumission 

In [18]:
test_df = test['text']

In [19]:
test_df = vectorizer.transform(test_df)

In [28]:
preds = svm.predict_proba(test_df)[:,1]

In [29]:
preds

array([9.80015788e-01, 1.92708933e-04, 3.38280571e-03, ...,
       1.27697202e-03, 8.03749872e-01, 9.52609027e-01])

In [30]:
ss = pd.read_csv("SampleSubmission.csv")

In [31]:
ss.head()

ID  target
0  test_2       0
1  test_3       0
2  test_4       0
3  test_8       0
4  test_9       0

In [32]:
ss['target'] = preds

In [34]:
ss.to_csv('Mercure.csv',index=False)

# Utilisation d'autre Algo

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [61]:
rf = LogisticRegression()

In [62]:
rf.fit(X_train, y_train)

LogisticRegression()

In [63]:
rf_pred = rf.predict(X_test)

In [64]:
accuracy_score(y_test , rf_pred)

0.8998109640831758

In [42]:
test_df

<1962x14292 sparse matrix of type '<class 'numpy.int64'>'
	with 31075 stored elements in Compressed Sparse Row format>

In [43]:
pred_rf = rf.predict_proba(test_df)[:,1]

In [45]:
pred_rf

array([0.81, 0.02, 0.12, ..., 0.08, 0.66, 0.85])

# creer un fichier submission et donne lui le nom sub_rf.csv

In [46]:
ss = pd.read_csv('SampleSubmission.csv')

In [47]:
ss.head()

ID  target
0  test_2       0
1  test_3       0
2  test_4       0
3  test_8       0
4  test_9       0